### ISSUE TITLE
input-remapper-control not starting

### ISSUE THREAD

**Issue by Degra02** [sezanzeb/input-remapper#772] opened 2023-09-18 07:54 UTC
OS: Arch Linux  
Kernel: 6.5.3-zen1-1-zen

Input-remapper build: `2.0.0.r6.g15eb0e96-1`

```bash
$ sudo pkill -f input-remapper && input-remapper-gtk -d
Traceback (most recent call last):
  File "/usr/bin/input-remapper-gtk", line 39, in <module>
    from inputremapper.gui.reader_service import ReaderService
  File "/usr/lib/python3.11/site-packages/inputremapper/gui/reader_service.py", line 55, in <module>
    from inputremapper.configs.input_config import InputCombination, InputConfig
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 51, in <module>
    class InputConfig(BaseModel):
  File "/usr/lib/python3.11/site-packages/inputremapper/configs/input_config.py", line 253, in InputConfig
    @root_validator
     ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 222, in root_validator
    return root_validator()(*__args)  # type: ignore
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

**Comment by hensansi** [comment] 2023-09-18 08:23
@Degra02 https://github.com/sezanzeb/input-remapper/issues/769#issuecomment-1722898896

**Comment by HerXtheSlayer** [comment] 2023-09-18 15:17
Same here on Garuda, started on Sep 17th, after a regular OS update.

**Comment by WyvernDotRed** [comment] 2023-09-18 16:43
Same issue again on both my Garuda Linux systems (Garuda uses the Arch Linux repos).
I suspect that the issue is related to the Pydantic update from 1.10.9-1 to 2.3.0-1, as found in this snippet of `pacman -Ss pydantic` output ran on a working snapshot:
`extra/python-pydantic 2.3.0-1 [installed: 1.10.9-1]
Data parsing and validation using Python type hints`

I will test downgrading this single package after the update and report on this with an edit of this comment.

In case some other package is the cause, here are the new version numbers of the python packages in this breaking update:
`python-aaf2-1.7.1-1  python-annotated-types-0.5.0-1  python-contourpy-1.1.1-1  python-gitpython-3.1.36-1  python-inflect-7.0.0-2  python-matplotlib-3.7.3-1  python-pillow-10.0.1-1  python-pydantic-2.3.0-1  python-pydantic-core-1:2.6.3-1  python-typing_extensions-4.8.0-1`

**Comment by sezanzeb** [comment] 2023-09-19 06:37
Should be fixed in https://github.com/sezanzeb/input-remapper/pull/773

**Closed by sezanzeb** 2023-09-19 06:37 UTC
