### ISSUE TITLE
Mouse dpi changes

### ISSUE THREAD

**Issue by creeperpaint** [sezanzeb/input-remapper#640] opened 2023-02-28 15:49 UTC
When injection is started, my mouse dpi goes up by a lot.

**Comment by sezanzeb** [comment] 2023-02-28 21:19
Possibly related: https://github.com/sezanzeb/input-remapper/issues/358

Which desktop environment are you using?

Wayland or X11?

**Comment by creeperpaint** [comment] 2023-03-01 13:11
X11 Plasma

**Comment by sezanzeb** [comment] 2023-03-01 18:27
Allright, then this is a duplicate of #358. Closing it therefore

**Closed by sezanzeb** 2023-03-01 18:27 UTC
Labels: environment incompatibility
