### ISSUE TITLE
Ignores five buttons out of entire keypad.

### ISSUE THREAD

**Issue by beaverrrr** [sezanzeb/input-remapper#517] opened 2022-10-27 21:45 UTC
Trying to bind `Alt L` key on Razer Tartarus Pro, using 1.6.0-beta. Have to use beta, only way apparent to remove mouse scroll from scroll wheel on the keypad. `Alt L` rebind worked on 1.5.0 version of input-remapper.
1. `input-remapper-control --version`
```
input-remapper 1.6.0-beta 94b94b9db63179bef365566ae6efa0a744d7e907 https://github.com/sezanzeb/input-remapper
python-evdev 1.6.0
```
2. which linux distro (ubuntu 20.04, manjaro, etc.)
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```
3. `echo $XDG_SESSION_TYPE`
`x11`
4. which desktop environment (gnome, plasma, xfce4, etc.)
`ubuntu:GNOME`
5. `sudo ls -l /proc/1/exe`
`lrwxrwxrwx 1 root root 0 Oct 27 14:48 /proc/1/exe -> /usr/lib/systemd/systemd`
7. paste the affected preset .json file from ~/.config/input-remapper/presets
Wouldn't allow me to attach pure json, but here it is:
[RoR.json.txt](https://github.com/sezanzeb/input-remapper/files/9883288/RoR.json.txt)
Mapping for the key that gets ignored:
```
    "1,56,1": {
        "target_uinput": "keyboard",
        "output_symbol": "KEY_J",
        "mapping_type": "key_macro"
    },
```
9. `sudo pkill -f input-remapper-service && input-remapper-gtk -d`, apply the preset and hit your key. Then share that log.
```
17:31:24.680891 15690 GUI-Helper DEBUG helper.py:294: to frontend: ·················· InputEvent(1, 56, 0)
17:31:24.706011 15681 GUI DEBUG reader.py:94: Reader received {'type': 'event', 'message': [1666906284, 680770, 1, 56, 0]}
17:31:24.706072 15681 GUI DEBUG reader.py:94: Reader received {'type': 'event', 'message': [1666906284, 680770, 1, 56, 0]}

```
10. `sudo evtest` while the previous command is running, to see how events are injected. Devices starting with `input-remapper ...` are of interest.
/dev/input/event30:	input-remapper keyboard
For all keys except `Alt L`:
```
Event: time 1666906396.768457, type 1 (EV_KEY), code 2 (KEY_1), value 1
Event: time 1666906396.768457, -------------- SYN_REPORT ------------
1Event: time 1666906396.867407, type 1 (EV_KEY), code 2 (KEY_1), value 0
Event: time 1666906396.867407, -------------- SYN_REPORT ------------
Event: time 1666906397.224356, type 1 (EV_KEY), code 3 (KEY_2), value 1
Event: time 1666906397.224356, -------------- SYN_REPORT ------------
2Event: time 1666906397.334346, type 1 (EV_KEY), code 3 (KEY_2), value 0
Event: time 1666906397.334346, -------------- SYN_REPORT ------------
Event: time 1666906397.502349, type 1 (EV_KEY), code 4 (KEY_3), value 1
Event: time 1666906397.502349, -------------- SYN_REPORT ------------
3Event: time 1666906397.625344, type 1 (EV_KEY), code 4 (KEY_3), value 0
Event: time 1666906397.625344, -------------- SYN_REPORT ------------
Event: time 1666906398.695342, type 1 (EV_KEY), code 5 (KEY_4), value 1
Event: time 1666906398.695342, -------------- SYN_REPORT ------------
4Event: time 1666906398.848379, type 1 (EV_KEY), code 5 (KEY_4), value 0
Event: time 1666906398.848379, -------------- SYN_REPORT ------------
Event: time 1666906399.175338, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 1
Event: time 1666906399.175338, -------------- SYN_REPORT ------------
Event: time 1666906399.301337, type 1 (EV_KEY), code 42 (KEY_LEFTSHIFT), value 0
Event: time 1666906399.301337, -------------- SYN_REPORT ------------
```
Nothing when `Alt L` is pressed.
I have also bound arrow keys and space keys for testing, as they work as intended without remapping, and arrow keys get ignored in a similar way as well.

**Comment by jonasBoss** [comment] 2022-10-28 09:14
that is strange, your mapping looks alright. 

can your run `sudo pkill input-remapper- && sudo input-remapper-service -d 2> IR-Service.txt` and then apply the mapping and press the ignored buttons? This will dump the debug log from the service to a "IR-Service.txt" file maybe we can find the issue in there.

**Comment by beaverrrr** [comment] 2022-11-01 22:38
> `sudo pkill input-remapper- && sudo input-remapper-service -d 2> IR-Service.txt`
When I ran that, IR-Service.txt was only a dozen lines long, so I had to redo it with `sudo input-remapper-gtk -d 2> IR-Service.txt `

There it is:
[IR-Service.txt](https://github.com/sezanzeb/input-remapper/files/9914391/IR-Service.txt)

**Comment by jonasBoss** [comment] 2022-11-02 15:23
I suspect that you have a issue similar to this: #435 

If you stop all injections and run `sudo evtest` do you see multiple devices with the name "Razer Tartarus Pro"?

Can you post the Supported events for each of the "Razer Tartarus Pro" devices?
Should look something like this:
```
Select the device event number [0-23]: 2
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x67 version 0x111
Input device name: "Razer Razer Naga Trinity"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
```

If you press the ignored buttons and not ignored buttons, are they reported on different devices in evtest? If so, on which?

**Comment by beaverrrr** [comment] 2022-11-02 21:40
`sudo evtest` lists 4 devices related to Tartarus:
```
/dev/input/event26:	Razer Razer Tartarus Pro
/dev/input/event27:	Razer Razer Tartarus Pro Keyboard
/dev/input/event28:	Razer Razer Tartarus Pro
/dev/input/event29:	Razer Razer Tartarus Pro
```
Device 26 reacts to Alt L and D-pad keys.
```
Select the device event number [0-29]: 26
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x244 version 0x111
Input device name: "Razer Razer Tartarus Pro"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 129 (KEY_AGAIN)
    Event code 130 (KEY_PROPS)
    Event code 131 (KEY_UNDO)
    Event code 132 (KEY_FRONT)
    Event code 133 (KEY_COPY)
    Event code 134 (KEY_OPEN)
    Event code 135 (KEY_PASTE)
    Event code 136 (KEY_FIND)
    Event code 137 (KEY_CUT)
    Event code 138 (KEY_HELP)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 150 (KEY_WWW)
    Event code 152 (KEY_SCREENLOCK)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 161 (KEY_EJECTCD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 173 (KEY_REFRESH)
    Event code 176 (KEY_EDIT)
    Event code 177 (KEY_SCROLLUP)
    Event code 178 (KEY_SCROLLDOWN)
    Event code 179 (KEY_KPLEFTPAREN)
    Event code 180 (KEY_KPRIGHTPAREN)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 186 (KEY_F16)
    Event code 187 (KEY_F17)
    Event code 188 (KEY_F18)
    Event code 189 (KEY_F19)
    Event code 190 (KEY_F20)
    Event code 191 (KEY_F21)
    Event code 192 (KEY_F22)
    Event code 193 (KEY_F23)
    Event code 194 (KEY_F24)
    Event code 240 (KEY_UNKNOWN)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 17 (EV_LED)
    Event code 0 (LED_NUML) state 1
    Event code 1 (LED_CAPSL) state 0
    Event code 2 (LED_SCROLLL) state 0
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
Properties:
Testing ... (interrupt to exit)
Event: time 1667424470.208816, type 17 (EV_LED), code 0 (LED_NUML), value 0
Event: time 1667424470.208816, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e2
Event: time 1667424470.208816, type 1 (EV_KEY), code 56 (KEY_LEFTALT), value 1
Event: time 1667424470.208816, -------------- SYN_REPORT ------------
Event: time 1667424470.366492, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e2
Event: time 1667424470.366492, type 1 (EV_KEY), code 56 (KEY_LEFTALT), value 0
Event: time 1667424470.366492, -------------- SYN_REPORT ------------
Event: time 1667424471.989806, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70051
Event: time 1667424471.989806, type 1 (EV_KEY), code 108 (KEY_DOWN), value 1
Event: time 1667424471.989806, -------------- SYN_REPORT ------------
^[[BEvent: time 1667424472.158496, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70051
Event: time 1667424472.158496, type 1 (EV_KEY), code 108 (KEY_DOWN), value 0
Event: time 1667424472.158496, -------------- SYN_REPORT ------------
Event: time 1667424472.576797, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70052
Event: time 1667424472.576797, type 1 (EV_KEY), code 103 (KEY_UP), value 1
Event: time 1667424472.576797, -------------- SYN_REPORT ------------
^[[AEvent: time 1667424472.701819, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70052
Event: time 1667424472.701819, type 1 (EV_KEY), code 103 (KEY_UP), value 0
Event: time 1667424472.701819, -------------- SYN_REPORT ------------
Event: time 1667424473.707806, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70050
Event: time 1667424473.707806, type 1 (EV_KEY), code 105 (KEY_LEFT), value 1
Event: time 1667424473.707806, -------------- SYN_REPORT ------------
^[[DEvent: time 1667424473.786590, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70050
Event: time 1667424473.786590, type 1 (EV_KEY), code 105 (KEY_LEFT), value 0
Event: time 1667424473.786590, -------------- SYN_REPORT ------------
Event: time 1667424474.167771, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7004f
Event: time 1667424474.167771, type 1 (EV_KEY), code 106 (KEY_RIGHT), value 1
Event: time 1667424474.167771, -------------- SYN_REPORT ------------
^[[CEvent: time 1667424474.322739, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7004f
Event: time 1667424474.322739, type 1 (EV_KEY), code 106 (KEY_RIGHT), value 0
Event: time 1667424474.322739, -------------- SYN_REPORT ------------
```

Device 27 reacts to all the normal keys + space.
```
Select the device event number [0-29]: 27
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x244 version 0x111
Input device name: "Razer Razer Tartarus Pro Keyboard"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 1 (KEY_ESC)
    Event code 2 (KEY_1)
    Event code 3 (KEY_2)
    Event code 4 (KEY_3)
    Event code 5 (KEY_4)
    Event code 6 (KEY_5)
    Event code 7 (KEY_6)
    Event code 8 (KEY_7)
    Event code 9 (KEY_8)
    Event code 10 (KEY_9)
    Event code 11 (KEY_0)
    Event code 12 (KEY_MINUS)
    Event code 13 (KEY_EQUAL)
    Event code 14 (KEY_BACKSPACE)
    Event code 15 (KEY_TAB)
    Event code 16 (KEY_Q)
    Event code 17 (KEY_W)
    Event code 18 (KEY_E)
    Event code 19 (KEY_R)
    Event code 20 (KEY_T)
    Event code 21 (KEY_Y)
    Event code 22 (KEY_U)
    Event code 23 (KEY_I)
    Event code 24 (KEY_O)
    Event code 25 (KEY_P)
    Event code 26 (KEY_LEFTBRACE)
    Event code 27 (KEY_RIGHTBRACE)
    Event code 28 (KEY_ENTER)
    Event code 29 (KEY_LEFTCTRL)
    Event code 30 (KEY_A)
    Event code 31 (KEY_S)
    Event code 32 (KEY_D)
    Event code 33 (KEY_F)
    Event code 34 (KEY_G)
    Event code 35 (KEY_H)
    Event code 36 (KEY_J)
    Event code 37 (KEY_K)
    Event code 38 (KEY_L)
    Event code 39 (KEY_SEMICOLON)
    Event code 40 (KEY_APOSTROPHE)
    Event code 41 (KEY_GRAVE)
    Event code 42 (KEY_LEFTSHIFT)
    Event code 43 (KEY_BACKSLASH)
    Event code 44 (KEY_Z)
    Event code 45 (KEY_X)
    Event code 46 (KEY_C)
    Event code 47 (KEY_V)
    Event code 48 (KEY_B)
    Event code 49 (KEY_N)
    Event code 50 (KEY_M)
    Event code 51 (KEY_COMMA)
    Event code 52 (KEY_DOT)
    Event code 53 (KEY_SLASH)
    Event code 54 (KEY_RIGHTSHIFT)
    Event code 55 (KEY_KPASTERISK)
    Event code 56 (KEY_LEFTALT)
    Event code 57 (KEY_SPACE)
    Event code 58 (KEY_CAPSLOCK)
    Event code 59 (KEY_F1)
    Event code 60 (KEY_F2)
    Event code 61 (KEY_F3)
    Event code 62 (KEY_F4)
    Event code 63 (KEY_F5)
    Event code 64 (KEY_F6)
    Event code 65 (KEY_F7)
    Event code 66 (KEY_F8)
    Event code 67 (KEY_F9)
    Event code 68 (KEY_F10)
    Event code 69 (KEY_NUMLOCK)
    Event code 70 (KEY_SCROLLLOCK)
    Event code 71 (KEY_KP7)
    Event code 72 (KEY_KP8)
    Event code 73 (KEY_KP9)
    Event code 74 (KEY_KPMINUS)
    Event code 75 (KEY_KP4)
    Event code 76 (KEY_KP5)
    Event code 77 (KEY_KP6)
    Event code 78 (KEY_KPPLUS)
    Event code 79 (KEY_KP1)
    Event code 80 (KEY_KP2)
    Event code 81 (KEY_KP3)
    Event code 82 (KEY_KP0)
    Event code 83 (KEY_KPDOT)
    Event code 85 (KEY_ZENKAKUHANKAKU)
    Event code 86 (KEY_102ND)
    Event code 87 (KEY_F11)
    Event code 88 (KEY_F12)
    Event code 89 (KEY_RO)
    Event code 90 (KEY_KATAKANA)
    Event code 91 (KEY_HIRAGANA)
    Event code 92 (KEY_HENKAN)
    Event code 93 (KEY_KATAKANAHIRAGANA)
    Event code 94 (KEY_MUHENKAN)
    Event code 95 (KEY_KPJPCOMMA)
    Event code 96 (KEY_KPENTER)
    Event code 97 (KEY_RIGHTCTRL)
    Event code 98 (KEY_KPSLASH)
    Event code 99 (KEY_SYSRQ)
    Event code 100 (KEY_RIGHTALT)
    Event code 102 (KEY_HOME)
    Event code 103 (KEY_UP)
    Event code 104 (KEY_PAGEUP)
    Event code 105 (KEY_LEFT)
    Event code 106 (KEY_RIGHT)
    Event code 107 (KEY_END)
    Event code 108 (KEY_DOWN)
    Event code 109 (KEY_PAGEDOWN)
    Event code 110 (KEY_INSERT)
    Event code 111 (KEY_DELETE)
    Event code 113 (KEY_MUTE)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 117 (KEY_KPEQUAL)
    Event code 119 (KEY_PAUSE)
    Event code 121 (KEY_KPCOMMA)
    Event code 122 (KEY_HANGUEL)
    Event code 123 (KEY_HANJA)
    Event code 124 (KEY_YEN)
    Event code 125 (KEY_LEFTMETA)
    Event code 126 (KEY_RIGHTMETA)
    Event code 127 (KEY_COMPOSE)
    Event code 128 (KEY_STOP)
    Event code 129 (KEY_AGAIN)
    Event code 130 (KEY_PROPS)
    Event code 131 (KEY_UNDO)
    Event code 132 (KEY_FRONT)
    Event code 133 (KEY_COPY)
    Event code 134 (KEY_OPEN)
    Event code 135 (KEY_PASTE)
    Event code 136 (KEY_FIND)
    Event code 137 (KEY_CUT)
    Event code 138 (KEY_HELP)
    Event code 139 (KEY_MENU)
    Event code 140 (KEY_CALC)
    Event code 142 (KEY_SLEEP)
    Event code 143 (KEY_WAKEUP)
    Event code 144 (KEY_FILE)
    Event code 150 (KEY_WWW)
    Event code 152 (KEY_SCREENLOCK)
    Event code 155 (KEY_MAIL)
    Event code 156 (KEY_BOOKMARKS)
    Event code 158 (KEY_BACK)
    Event code 159 (KEY_FORWARD)
    Event code 161 (KEY_EJECTCD)
    Event code 163 (KEY_NEXTSONG)
    Event code 164 (KEY_PLAYPAUSE)
    Event code 165 (KEY_PREVIOUSSONG)
    Event code 166 (KEY_STOPCD)
    Event code 167 (KEY_RECORD)
    Event code 168 (KEY_REWIND)
    Event code 169 (KEY_PHONE)
    Event code 171 (KEY_CONFIG)
    Event code 172 (KEY_HOMEPAGE)
    Event code 173 (KEY_REFRESH)
    Event code 174 (KEY_EXIT)
    Event code 176 (KEY_EDIT)
    Event code 177 (KEY_SCROLLUP)
    Event code 178 (KEY_SCROLLDOWN)
    Event code 179 (KEY_KPLEFTPAREN)
    Event code 180 (KEY_KPRIGHTPAREN)
    Event code 181 (KEY_NEW)
    Event code 183 (KEY_F13)
    Event code 184 (KEY_F14)
    Event code 185 (KEY_F15)
    Event code 186 (KEY_F16)
    Event code 187 (KEY_F17)
    Event code 188 (KEY_F18)
    Event code 189 (KEY_F19)
    Event code 190 (KEY_F20)
    Event code 191 (KEY_F21)
    Event code 192 (KEY_F22)
    Event code 193 (KEY_F23)
    Event code 194 (KEY_F24)
    Event code 206 (KEY_CLOSE)
    Event code 207 (KEY_PLAY)
    Event code 208 (KEY_FASTFORWARD)
    Event code 209 (KEY_BASSBOOST)
    Event code 210 (KEY_PRINT)
    Event code 212 (KEY_CAMERA)
    Event code 216 (KEY_CHAT)
    Event code 217 (KEY_SEARCH)
    Event code 219 (KEY_FINANCE)
    Event code 224 (KEY_BRIGHTNESSDOWN)
    Event code 225 (KEY_BRIGHTNESSUP)
    Event code 228 (KEY_KBDILLUMTOGGLE)
    Event code 229 (KEY_KBDILLUMDOWN)
    Event code 230 (KEY_KBDILLUMUP)
    Event code 234 (KEY_SAVE)
    Event code 235 (KEY_DOCUMENTS)
    Event code 240 (KEY_UNKNOWN)
    Event code 241 (KEY_VIDEO_NEXT)
    Event code 244 (KEY_BRIGHTNESS_ZERO)
    Event code 256 (BTN_0)
    Event code 353 (KEY_SELECT)
    Event code 354 (KEY_GOTO)
    Event code 358 (KEY_INFO)
    Event code 362 (KEY_PROGRAM)
    Event code 366 (KEY_PVR)
    Event code 370 (KEY_SUBTITLE)
    Event code 372 (KEY_ZOOM)
    Event code 374 (KEY_KEYBOARD)
    Event code 375 (KEY_SCREEN)
    Event code 376 (KEY_PC)
    Event code 377 (KEY_TV)
    Event code 378 (KEY_TV2)
    Event code 379 (KEY_VCR)
    Event code 380 (KEY_VCR2)
    Event code 381 (KEY_SAT)
    Event code 383 (KEY_CD)
    Event code 384 (KEY_TAPE)
    Event code 386 (KEY_TUNER)
    Event code 387 (KEY_PLAYER)
    Event code 389 (KEY_DVD)
    Event code 392 (KEY_AUDIO)
    Event code 393 (KEY_VIDEO)
    Event code 396 (KEY_MEMO)
    Event code 397 (KEY_CALENDAR)
    Event code 398 (KEY_RED)
    Event code 399 (KEY_GREEN)
    Event code 400 (KEY_YELLOW)
    Event code 401 (KEY_BLUE)
    Event code 402 (KEY_CHANNELUP)
    Event code 403 (KEY_CHANNELDOWN)
    Event code 405 (KEY_LAST)
    Event code 407 (KEY_NEXT)
    Event code 408 (KEY_RESTART)
    Event code 409 (KEY_SLOW)
    Event code 410 (KEY_SHUFFLE)
    Event code 412 (KEY_PREVIOUS)
    Event code 416 (KEY_VIDEOPHONE)
    Event code 417 (KEY_GAMES)
    Event code 418 (KEY_ZOOMIN)
    Event code 419 (KEY_ZOOMOUT)
    Event code 420 (KEY_ZOOMRESET)
    Event code 421 (KEY_WORDPROCESSOR)
    Event code 422 (KEY_EDITOR)
    Event code 423 (KEY_SPREADSHEET)
    Event code 424 (KEY_GRAPHICSEDITOR)
    Event code 425 (KEY_PRESENTATION)
    Event code 426 (KEY_DATABASE)
    Event code 427 (KEY_NEWS)
    Event code 428 (KEY_VOICEMAIL)
    Event code 429 (KEY_ADDRESSBOOK)
    Event code 430 (KEY_MESSENGER)
    Event code 431 (KEY_DISPLAYTOGGLE)
    Event code 432 (KEY_SPELLCHECK)
    Event code 433 (KEY_LOGOFF)
    Event code 439 (KEY_MEDIA_REPEAT)
    Event code 442 (KEY_IMAGES)
    Event code 576 (KEY_BUTTONCONFIG)
    Event code 577 (KEY_TASKMANAGER)
    Event code 578 (KEY_JOURNAL)
    Event code 579 (KEY_CONTROLPANEL)
    Event code 580 (KEY_APPSELECT)
    Event code 581 (KEY_SCREENSAVER)
    Event code 582 (KEY_VOICECOMMAND)
    Event code 583 (KEY_ASSISTANT)
    Event code 585 (?)
    Event code 586 (?)
    Event code 592 (KEY_BRIGHTNESS_MIN)
    Event code 593 (KEY_BRIGHTNESS_MAX)
  Event type 2 (EV_REL)
    Event code 6 (REL_HWHEEL)
    Event code 12 (REL_HWHEEL_HI_RES)
  Event type 3 (EV_ABS)
    Event code 32 (ABS_VOLUME)
      Value      0
      Min        0
      Max      572
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Key repeat handling:
  Repeat type 20 (EV_REP)
    Repeat code 0 (REP_DELAY)
      Value    250
    Repeat code 1 (REP_PERIOD)
      Value     33
Properties:
Testing ... (interrupt to exit)
Event: time 1667424543.022915, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001e
Event: time 1667424543.022915, type 1 (EV_KEY), code 2 (KEY_1), value 1
Event: time 1667424543.022915, -------------- SYN_REPORT ------------
1Event: time 1667424543.093576, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001e
Event: time 1667424543.093576, type 1 (EV_KEY), code 2 (KEY_1), value 0
Event: time 1667424543.093576, -------------- SYN_REPORT ------------
Event: time 1667424543.676944, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1667424543.676944, type 1 (EV_KEY), code 3 (KEY_2), value 1
Event: time 1667424543.676944, -------------- SYN_REPORT ------------
2Event: time 1667424543.770705, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7001f
Event: time 1667424543.770705, type 1 (EV_KEY), code 3 (KEY_2), value 0
Event: time 1667424543.770705, -------------- SYN_REPORT ------------
Event: time 1667424544.238957, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70020
Event: time 1667424544.238957, type 1 (EV_KEY), code 4 (KEY_3), value 1
Event: time 1667424544.238957, -------------- SYN_REPORT ------------
3Event: time 1667424544.308969, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70020
Event: time 1667424544.308969, type 1 (EV_KEY), code 4 (KEY_3), value 0
Event: time 1667424544.308969, -------------- SYN_REPORT ------------
```

Device 28 apparently processes no keys.
```
Select the device event number [0-29]: 28
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x244 version 0x111
Input device name: "Razer Razer Tartarus Pro"
Supported events:
  Event type 0 (EV_SYN)
  Event type 3 (EV_ABS)
    Event code 40 (ABS_MISC)
      Value      0
      Min        0
      Max      255
Properties:
Testing ... (interrupt to exit)
12345	qwerasdfZXC
```
   
Device 29 is a mouse, or, rather, a mouse wheel.
```
Select the device event number [0-29]: 29
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x1532 product 0x244 version 0x111
Input device name: "Razer Razer Tartarus Pro"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 8 (REL_WHEEL)
    Event code 11 (REL_WHEEL_HI_RES)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
Event: time 1667424672.861072, type 2 (EV_REL), code 8 (REL_WHEEL), value -1
Event: time 1667424672.861072, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value -120
Event: time 1667424672.861072, -------------- SYN_REPORT ------------
Event: time 1667424673.970069, type 2 (EV_REL), code 8 (REL_WHEEL), value 1
Event: time 1667424673.970069, type 2 (EV_REL), code 11 (REL_WHEEL_HI_RES), value 120
Event: time 1667424673.970069, -------------- SYN_REPORT ------------
Event: time 1667424674.784095, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1667424674.784095, type 1 (EV_KEY), code 274 (BTN_MIDDLE), value 1
Event: time 1667424674.784095, -------------- SYN_REPORT ------------
   
Event: time 1667424674.977138, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90003
Event: time 1667424674.977138, type 1 (EV_KEY), code 274 (BTN_MIDDLE), value 0
Event: time 1667424674.977138, -------------- SYN_REPORT ------------
^[[B^[[D^[[A^[[C^[[B^[[D 1234	qwerASDFzxc         

```

Razer, apparently, doesn't only make horrible drivers, it also engineers horrible devices to be driven by them. If I had any alternative to this thing for my use case, I'd toss it immediately.

**Comment by jonasBoss** [comment] 2022-11-03 18:23
This confirms my suspicion. This was caused by https://github.com/jonasBoss/key-mapper/commit/a622037834a824d534c8736203e3799538c9fd0b, the partial fix for #435. 

Both device 26 and 27 can process the same events, so InputRemapper does no know which device is the correct one to use.

I will close this because it is fundamentally the same issue as #435. Properly fixing that will also resolve this.

**Closed by jonasBoss** 2022-11-03 18:23 UTC

**Comment by jonasBoss** [comment] 2022-12-02 22:48
#550 should fix this. You will need to record the input for the affected mappings again. 
It would be super helpful if you can test it.

**Comment by beaverrrr** [comment] 2022-12-06 21:18
I have tried to update input-remapper to test this, and currently on this version:
```
16:01:09.083993 29245 GUI INFO logger.py:267: input-remapper-gtk 1.6.0-beta bb6e4d23fea244530fd5610d7799f541c55e1b4a https://github.com/sezanzeb/input-remapper
16:01:09.084051 29245 GUI INFO logger.py:275: python-evdev 1.6.0
```

When input-remapper is running, and preset is applied, no inputs are being processed from Dpad/LAlt device, they don't appear in input-remapper log in any way, which is the same behavior as before, and I suspect that's because #550 is not in main beta branch yet, and I am not fluent enough in git to pull a specific draft, commit, or pull request (?), to build it here.
