### ISSUE TITLE
Ghost gamepad in dev/input

### ISSUE THREAD

**Issue by Yueh72** [sezanzeb/input-remapper#321] opened 2022-02-28 13:12 UTC
Every time the service is launch it create a fake gamepad input (xbox 360) wich cause trouble with Steam.
Delete the input file solve the problem, but i must do it every time i start my computer or restart the service.

Here's the input-remapper-gtk -d line concerned : 

 GUI-Helper DEBUG groups.py:378: Found "3_1_1_input-remapper", "/dev/input/event20", "input-remapper gamepad", type: gamepad

There's no gamepad in my usb of course.

**Comment by jonasBoss** [comment] 2022-02-28 13:57
What are the issues you are experiencing? The "ghost" gamepad is created on purpose, but maybe we can make some changes to it, so that it doesn't cause issues.

The "input-remapper gamepad" is created so that Input-Remapper is able to make keybindings for a gamepad. It should not do anything if you don't have a mapping with the `gamepad` as target. Deleting the `/dev/input/eventXX` will probably brake Input-Remapper partially.

**Comment by jonasBoss** [comment] 2022-02-28 15:25
Yeah, that sounds like a conflict with steaminput. But I think it should be possible to resolve those within Steam: 
If you go to the "Properties" menu for a game, there is a tab called "CONTROLLER" from there you can override how steam handles controllers, maybe that helps.

I have plans to allow users to create their own Input devices in Input-Remapper and also to enable or disable them. But that has to wait until I am finished with #263 and I am currently busy with University exams.

**Comment by vadim212112** [comment] 2022-03-01 22:45
i hawe same problem in steam games
warthunder. another games not test
the mouse moves to the lower left corner and does not move, and the game reports the controller
enable or disable steam input system not help me
xbox gamepad connect always

**Comment by sezanzeb** [comment] 2022-03-02 12:40
Maybe it would make sense to lazy-load the individual uinputs.

The service could look up if the specified target exists before injection, and if not create it.

Lazy loading has helped with other issues in the past already to avoid problematic interactions during boot, I'm quite a fan of it.

**Comment by delcake** [comment] 2022-03-12 05:16
I'm definitely in favor of being able to disable the remapper gamepad since I've found that Retroarch has an even shot of picking my actual controller or the input-remapper gamepad as the default controller when launching, which creates a situation where half of the time I need to go in to my configuration and manually specify the correct device before being able to play.

As I don't make use of the program's gamepad mapping features for anything, it seems to be getting in the way for no benefit currently.

**Comment by Merrit** [comment] 2022-03-12 13:52
I have noticed several games will only ever use the _first_ gamepad listed, and since the system doesn't see my controller until it is turned on the input-remapper gamepad is always the first - and so multiple games won't react to the real controller.

**Comment by Zorrototo** [comment] 2022-03-14 13:08
I have similar issue with CEMU emulator, the gamepad (Xbox 360 Controller) doesn't work when Input Remapper service is enabled and working. If I reboot with the service disabled it works in CEMU, moving the joysticks moves the cursors in the Input Configuration menu. If I enable the service and reboot CEMU can not work with the Xbox 360 controller. I don't have any configuration made in Input Remapper for the Xbox 360 Controller that could interfere.

In Steam games I need to enable the Xbox Support in Controller Settings in order to be ble to use the Xbox 360 controller in GTA 5 for example, when Input Remapper service is enabled and working.

In Steam Controller Settings, I can see two controllers (one called `Xbox 360 Controller : Xbox 360 Controller` and the other one called `Xbox 360 Controller`, despite having only one plugged in.

I think the problem should be fixed on Input Remapper side so in these various reproducible cases it doesn't stop the controller from being usable. Hope a solution is found.

**Comment by sezanzeb** [comment] 2022-03-15 00:04
Try this: https://github.com/sezanzeb/input-remapper/pull/339

**Comment by Zorrototo** [comment] 2022-03-15 00:57
Seems like it is working from a quick look. Didn't do extensive tests but I don't have the second ghost controller in Steam Controller Settings, and a quick test in CEMU shows the controller inputs when used.
:+1:

**Comment by sezanzeb** [comment] 2022-03-17 09:32
Fix is on main

**Closed by sezanzeb** 2022-03-17 09:32 UTC

**Comment by yarikus** [comment] 2022-06-18 12:02
I should say It doesn't work in my case. I installed 1.4.2 from AUR and I still have two gamepads in Steam. I even tried to install beta version, but no results.

**Comment by sezanzeb** [comment] 2022-06-19 15:37
if you run `sudo evtest` there should be no "input-remapper gamepad" device, unless you have a preset that uses the gamepad target

![image](https://user-images.githubusercontent.com/28510156/174488966-62d8307b-ea67-45e8-ac44-528943608811.png)

can you verify that please?

**Comment by yarikus** [comment] 2022-06-20 22:18
I didn't notice any difference with `sudo evtest`. I have my gamepad in the devices list and also I can change a key.

![Screenshot from 2022-06-21 00-11-21](https://user-images.githubusercontent.com/634360/174683559-891d47af-c833-40ed-817f-9de46c9680f1.png)

I have a ghost gamepad only in combination with Steam. If I run Stream and Input Remapper together in this case I have an odd X-Box 360 gamepad in the list.

**Comment by yarikus** [comment] 2022-06-21 12:55
I have only these ones:

```
/dev/input/event258:  input-remapper keyboard
/dev/input/event259:  input-remapper Microsoft X-Box One pad forwarded
```
And after stop injection I still have `input-remapper keyboard`, but it is not `input-remapper gamepad` as you said.

**Comment by sezanzeb** [comment] 2022-06-21 15:17
if the "forwarded" device is causing the issue, then this might require changes on steams side. We can't get rid of this, it is fundamental to how input-remapper works. It seems their issue tracker is here: https://github.com/ValveSoftware/steam-for-linux/issues

> and I still have two gamepads in Steam

what kind of problem exactly is this causing for you? This information is probably important for them in detail. Then we can maybe move this to their issue tracker.
