### ISSUE TITLE
Pepper Jobs Remote Control Cannot Record

### ISSUE THREAD

**Issue by abrombo** [sezanzeb/input-remapper#698] opened 2023-05-02 15:45 UTC
I have a "Pepper Jobs" Remote control which input-remapper 2.0.0 on ubuntu 20.04 recognizes as a "W10 GYRO W10 GYRO" but I cannot record any buttons from the device.  I an not sure but Xev shows output from the device and I think it is outputting Win 10 macro commands.  Here is a link mentioning using this device with linux -

https://www.reddit.com/r/htpc/comments/bt66vy/w10_gyro_htpc_remote/

Any suggestions would be appreciated.

**Comment by abrombo** [comment] 2023-05-02 19:29
I reverted to version 1.5.0 and everything worked.  Also I could not get any of my devices mapped with version 2.0.

**Comment by abrombo** [comment] 2023-05-02 20:37
For me version 2.0 works on ubuntu 22.04 and version 1.5 works on ubuntu 20.04 (I use ubuntu 20.04 for my htpc's since it wakes from suspend quicker than ubuntu 22.04).

**Comment by mickeyl** [comment] 2023-05-12 08:43
Duplicate of #676

**Closed** 2023-08-17 07:36 UTC
