### ISSUE TITLE
[Feature Request] Run Terminal commands/Open Applications

### ISSUE THREAD

**Issue by im-AMS** [sezanzeb/input-remapper#330] opened 2022-03-04 10:39 UTC
Is there a way we can map terminal commands to keybindings?

It would be quite streamlined, one app solution to manage keymaps irrespective of Desktop Env. it can be as simple as copying config file to other installations.

**Examples**

- map `Ctrl+Alt+T` to run `kitty` or `gnome-terminal`
- map `ctrl+alt+f` to run `firefox`

**Comment by sezanzeb** [comment] 2022-03-04 14:58
Thanks for the feature request. This is a duplicate of https://github.com/sezanzeb/input-remapper/issues/234 though

**Closed by sezanzeb** 2022-03-04 14:58 UTC
