### ISSUE TITLE
combinations not working in Hyprland

### ISSUE THREAD

**Issue by herlev** [sezanzeb/input-remapper#515] opened 2022-10-24 15:13 UTC
On X the following config allows me to swap Control_L and Alt_L:
```json
{
    "mapping": {
        "1,29,1": [
            "Alt_L",
            "keyboard"
        ],
        "1,56,1": [
            "Control_L",
            "keyboard"
        ]
    }
}
```
However this is not working on Wayland.

## Info
```
~ ➤ input-remapper-control --version
input-remapper 1.5.0 aa6a50584064f36f3658b5aa5530549d9c7ebd50 https://github.com/sezanzeb/input-remapper
python-evdev 1.6.0
~ ➤ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	22.0.0
Codename:	Sikaris
~ ➤ echo $XDG_SESSION_TYPE
wayland
~ ➤ sudo ls -l /proc/1/exe
lrwxrwxrwx 1 root root 0 Oct 24 15:55 /proc/1/exe -> /usr/lib/systemd/systemd
~ ➤ echo $XDG_CURRENT_DESKTOP
Hyprland
```
## Testing

Pressing Alt-c (which on X results in Ctrl-c) results in the character `c` being output:

```
~ ➤ sudo pkill -f input-remapper-service && sudo input-remapper-gtk -d
...
17:02:20.394620 11184 Service DEBUG keycode_mapper.py:541: maps to (29, keyboard) ········ ((1, 56, 1))
17:02:21.425588 11184 Service DEBUG keycode_mapper.py:392: unknown combination ··········· ((1, 56, 1), (1, 46, 1))
17:02:21.425821 11184 Service DEBUG keycode_mapper.py:551: forwarding ···················· ((1, 46, 1))
c17:02:21.549231 11184 Service DEBUG keycode_mapper.py:469: forwarding release ············ ((1, 46, 0))
17:02:21.842546 11184 Service DEBUG keycode_mapper.py:456: releasing (29, keyboard) ······ ((1, 56, 0))
...
```
```
~ ➤ wev -f wl_keyboard
[14:     wl_keyboard] key: serial: 4267; time: 1120521; key: 37; state: 1 (pressed)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 65424
[14:     wl_keyboard] repeat_info: rate: 50 keys/sec; delay: 200 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 4270; time: 1123228; key: 54; state: 1 (pressed)
                      sym: c            (99), utf8: 'c'
[14:     wl_keyboard] key: serial: 4271; time: 1123348; key: 54; state: 0 (released)
                      sym: c            (99), utf8: ''
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 65424
[14:     wl_keyboard] repeat_info: rate: 50 keys/sec; delay: 200 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 4273; time: 1124090; key: 37; state: 0 (released)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

Based on the wev output, it seems like the key is getting remapped, but the modifiers are being changed before sending the `c` key.

**Comment by sezanzeb** [comment] 2022-10-24 23:04
does it work if you map "c" to "c" in addition to the existing configuration?

This makes the c go through the "input-remapper keyboard" device instead of "input-remapper forwarded"

**Comment by herlev** [comment] 2022-10-25 10:33
Yes it does. Any way to make this the default behavior, so that I don't have to create mappings for all keys I want to use in combination with ctrl and alt?

**Comment by sezanzeb** [comment] 2022-10-25 17:04
Do you have a second keyboard lying around by any chance? If yes, connect it, stop input-remapper, hit "ctrl" on the one, and "c" on the other, what happens?

Maybe we could offer an option to send all key events through the "keyboard" target instead of forwarding. But I would only do that as a last resort

**Comment by sezanzeb** [comment] 2022-10-25 17:05
I need to try it out on wayland myself later

**Comment by herlev** [comment] 2022-10-25 17:23
I tried it with a second keyboard "ctrl-c", when pressed on two different keyboards results in "c" being output.

#### `wev -f wl_keyboard`, "ctrl-c" pressed on two different keyboards
```
[14:     wl_keyboard] key: serial: 17352; time: 11493861; key: 37; state: 1 (pressed)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 65424
[14:     wl_keyboard] repeat_info: rate: 50 keys/sec; delay: 200 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 17355; time: 11498403; key: 54; state: 1 (pressed)
                      sym: c            (99), utf8: 'c'
[14:     wl_keyboard] key: serial: 17356; time: 11498480; key: 54; state: 0 (released)
                      sym: c            (99), utf8: ''
[14:     wl_keyboard] keymap: format: 1 (xkb v1), size: 65424
[14:     wl_keyboard] repeat_info: rate: 50 keys/sec; delay: 200 ms
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 17358; time: 11504005; key: 37; state: 0 (released)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

#### `wev -f wl_keyboard`, "ctrl-c" pressed on the same keyboard
```
[14:     wl_keyboard] key: serial: 18149; time: 11703045; key: 37; state: 1 (pressed)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000004: Control 
                      latched: 00000000
                      locked: 00000000
[14:     wl_keyboard] key: serial: 18151; time: 11703853; key: 54; state: 1 (pressed)
                      sym: c            (99), utf8: ''
[14:     wl_keyboard] key: serial: 18152; time: 11703957; key: 54; state: 0 (released)
                      sym: c            (99), utf8: ''
[14:     wl_keyboard] key: serial: 18153; time: 11704557; key: 37; state: 0 (released)
                      sym: Control_L    (65507), utf8: ''
[14:     wl_keyboard] modifiers: serial: 0; group: 0
                      depressed: 00000000
                      latched: 00000000
                      locked: 00000000
```

**Comment by herlev** [comment] 2022-10-25 18:11
I can successfully swap the keys using [kbct](https://github.com/samvel1024/kbct). However, it looks like it is using only one keyboard device to send the keys through (which I believe is what you are trying to avoid).

`sudo evtest`, when using kbct:
```
/dev/input/event17:	Kbct-AT Translated Set 2 keyboard
```

When using input-remapper:
```
/dev/input/event16:	input-remapper keyboard
/dev/input/event17:	input-remapper AT Translated Set 2 keyboard forwarded
```

**Comment by sezanzeb** [comment] 2022-10-25 19:33
> I need to try it out on wayland myself later

can't reproduce in kde on wayland

**Comment by sezanzeb** [comment] 2022-10-25 19:40
> I tried it with a second keyboard "ctrl-c", when pressed on two different keyboards results in "c" being output.

Sounds like your desktop environment could be the problem, since this can be reproduced without input-remapper.

I'd maybe post the issue at https://github.com/hyprwm/Hyprland

**Comment by sezanzeb** [comment] 2022-10-30 12:24
I'll close this now, because it seems to be related to the DE, not input-remapper

**Closed by sezanzeb** 2022-10-30 12:24 UTC
Labels: environment incompatibility
